language: c
os: linux
dist: focal
services:
  - docker

# Don't build the update-dependencies-pr branch; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^update-dependencies-pr/

cache:
  directories:
    - ${HOME}/buildx-cache/

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: "MZ71qG6CEk2xvHtWdb7Byq2lW9cJsbrW1CnQ10nR1fuTCJg0Ye7OAp2m9BuYTQj+xAiGrTR7Uz8xUbWYdazxCuCfuzB+uwVn2AibvsNKWeZ70fftZ31MBB/rJ8vdgNNU4zvJMPX5PjrE0/KmLufwlCOE2eDNkK+fVQAVy8ra+6uXvbENKJQthbyliHTAAj1eUeIl/dmOs1oCE/EeTyzVMX4ZUsfprE5zplDe99Qrx+D0/JrdRNok4D4ubthCnGMH4VCziggT6H3SefJ0Q4Vq5hLnlqNg+02wKpPRbrz+5ZwOdhDi09uXgWN2AOuz0KhxOsvPyToh7MYEEZAse7dh4eaqCJkiHaz8udYcHXPaGunfKVVadO2uLBSr34g65AxmIs2+qPg1lRZ4lqjFIE7QSoRKLMqBrRzPKkAZFgtb5bumMr4mOofY/CJlv9xS4CDUH86UGi9aJ+ksMAi2qJtvc0Bu8f2yyY5/itRiObaPfr/eNbxs2BwDdeGLwtn8Aj94bJoq4luzk17sOkZ05dgWW4hb/UesN76ZLY0zmZGjmeB166cub9P8xVQvK+JyEenqkfL3pka4dTzcmfmmhKjydwT8emIJ1MBaDpdzg0oKP1isFks1OzqQA6JmVsy1YQ0PJvTa/HmB0La3Gd5uQn4THQJFU5sMQYkfNjRLnBJN1qM="
    - secure: "k/AYe9ZNk5tvv/MV7hGGXpW2SVoc15yvQMokMG3yiIjvLubaD/+7IXo02iVrs3v2yiFk7Y5KxTq7lfZ4xyH3snFR/R4Qspd4Hpl6pblLdJNPW4z18605YBk/IIGYgDqUxfJzPKfzm5e19d4wCoPn/eW+kpm9Qgljz/dh2dweERMEoU+d4X66WEHhAo8QOo46nvOg9c+BCn4hImtAx8PkBWirLSSpyGDA6uOvcQl2DixI64H+yVh3PWFAy0otwP+pdLp/LxV6Mb5bUzv31YlQzVNlc8x5hGJYO4t4jisgH/VJAtljBkT/WMRyVpvWoGGGWIOBYPL+nubCproxlmGQTjAvgSSWTdWdCQKWDUmvzU7vI6TipkoJ7d3SE5D8eY0ZydLghcv1wnmQqcBub/K+GRjI4YzTyGapFsZ/O+k+UcdvhAeQ++vf+sFnymcDk6EccMQewfywVhObc8ZcDmuWqKaz7SET0h+UsVA25s306QoyWQYxz+K7cqrJZckurgxCq1gqbRRKhJyl3DtdeAE3rCx5Y2+0JszELsO+unQFNYTo17EWpFIhvHWSw5DJTyHKqI7CBFGnhd3xCu+4/w5dt1DwerpbT4FU/wc6iN1wHgLvgrm9u/3Rxir/bLHiCHswAIaLIpxS8+k/PAUfLQl9gOAyQEIhu/DhGAAuznGmT2M="

jobs:
   include:
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux2014" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux2014" PLATFORM="s390x"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux_2_24" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux_2_24" PLATFORM="s390x"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="musllinux_1_1" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="musllinux_1_1" PLATFORM="s390x"

before_install:
  - if [ -d "${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM}" ]; then cp -rlf ${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM} ./; fi

install:
  - nproc
  - free
  - ./travisci-install-buildx.sh

script:
  - COMMIT_SHA=${TRAVIS_COMMIT} ./build.sh
  - if [ -d "${HOME}/buildx-cache" ]; then rm -rf ${HOME}/buildx-cache; fi
  - mkdir ${HOME}/buildx-cache
  - cp -rlf ./.buildx-cache-* ${HOME}/buildx-cache/

deploy:
  provider: script
  script: COMMIT_SHA=${TRAVIS_COMMIT} ./deploy.sh
  on:
    branch: main
    repo: MarshalX/manylinux-cpython-pathes

after_script:
  - if [ -f ${HOME}/dockerd-rootless.pid ]; then kill -15 $(cat ${HOME}/dockerd-rootless.pid); fi
  - if [ -f /tmp/buildkitd.pid ]; then sudo kill -15 $(cat /tmp/buildkitd.pid); fi
